on: [push, pull_request]

jobs:
  python-lint:
    runs-on: ubuntu-latest
    name: CI workflow
    steps:
    - name: checkout source repo
      uses: actions/checkout@v2

    - name: linting
      uses: alexanderdamiani/pylinter@v1.2.0
      
    - name: wemake-python-styleguide
      uses: wemake-services/wemake-python-styleguide@0.15.3
